name: Ecommerce Test

on: [push, pull_request]

jobs:

  test:
    name: Test Code
    runs-on: ${{ matrix.ubuntu }}
    strategy:
      matrix:
        ubuntu: ["ubuntu-latest"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Docker Container
        run: docker-compose up -d
